services:
  fastapi:
#    image: registry.diginfra.net/tsd/athenstest:latest
    image: vicding81/athenstest:latest
    container_name: fastapi
    hostname: fastapi
    volumes:
      - "./sample_data:/app/data"
    command: [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    ports:
      - "8000:8000"


  prism:
    image: stoplight/prism:4
    container_name: prism
    hostname: prism
    init: true
    volumes:
      - "./skg-if-api.yaml:/tmp/skg-if-api.yaml"
    command: ["proxy", "-h", "0.0.0.0", "/tmp/skg-if-api.yaml", "http://fastapi:8000", "--errors"]
    ports:
      - "4010:4010"
