services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    volumes:
      - "./sample_data:/app/data"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"


  prism:
    image: stoplight/prism:4
    container_name: prism
    hostname: prism
    init: true
    volumes:
      - "./skg-if-api.yaml:/tmp/skg-if-api.yaml"
    command: ["proxy", "-h", "0.0.0.0", "/tmp/skg-if-api.yaml", "http://nginx:8000", "--errors"]
    ports:
      - "4010:4010"
