name: Validate Files

on:
  push:
    paths:
      - '**/*.json' # Adjust this to match the file types you want to validate

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx 

    - name: Get changed files for push
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "Changed files: $CHANGED_FILES"

    - name: Validate files
      run: |
        echo "Validating the following files: $CHANGED_FILES"
        python .github/scripts/validate_files.py
      env:
        CHANGED_FILES: ${{ env.CHANGED_FILES }}
