name: Validate Files

on:
  push:
    paths:
      - '**/*.json' # Adjust this to match the file types you want to validate

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx 

    - name: Validate files
      run: |
        python .github/scripts/validate_files.py
