name: Validate Files

on:
  push:
    paths:
      - '**/*.json' # Adjust this to match the file types you want to validate

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx 

    - name: Get changed files for push
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | tr '\n' ' ')
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
        echo "Changed files: $CHANGED_FILES"

    - name: Get openapi spec
      run: |
        echo "Fetching OpenAPI spec..."
        curl -o skg-if-api.yaml https://gitlab.esrf.fr/smis/ostrails/-/raw/main/skg-if-api/skg-if-api.yaml
        echo "OpenAPI spec fetched successfully."

    - name: Run Docker Compose
      run: |
        echo "Running Docker Compose..."
        docker compose -f docker-compose-validation.yml up -d

    - name: Test if docker is ready
      run: |
        echo "Waiting for Docker containers to be ready..."
        while ! curl -s http://localhost:4010/ > /dev/null; do
        docker logs prism
        sleep 5
        done
        while ! curl -s http://localhost:8000/ > /dev/null; do
        docker logs fastapi
        sleep 5
        done
        echo "Docker containers are ready."
        curl http://localhost:8000/

    - name: Validate files
      run: |
        echo "Validating the following files: $CHANGED_FILES"
        python .github/scripts/validate_files.py
      env:
        CHANGED_FILES: ${{ env.CHANGED_FILES }}
