name: Validate Files

on:
  push:
    paths:
      - '**/*.json' # Adjust this to match the file types you want to validate

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx 

    - name: Get changed files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }})
        echo "github.base_ref: ${{ github.base_ref }}"  # Debugging output
        echo "github.head_ref: ${{ github.head_ref }}"  # Debugging output
        echo "CHANGED_FILES: $CHANGED_FILES"  # Debugging output
        echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Validate files
      run: |
        python .github/scripts/validate_files.py $CHANGED_FILES
      env:
        CHANGED_FILES: $CHANGED_FILES
